### ISSUE TITLE
Applying this rule for unordeded list only

### ISSUE THREAD

**Issue by amimas** [azu/textlint-rule-period-in-list-item#2]
Is it possible to configure this rule so that it's applied to unordered type lists only and ignore ordered lists? If this is not available, can it be enhanced with for this configuration?

**Comment by azu** [comment]
Currently, that option is not implemented yet.

It is reasonable that we add `allowOrderedList` option for resoloving this issue.

**Comment by azu** [comment]
We have implemented `allowOrderedList` option(default: `false`) and released it.
Please try to confirm textlint-rule-period-in-list-item@0.3.0

**Comment by amimas** [comment]
Thanks a lot. I will try it soon.

**Comment by amimas** [comment]
Just writing to say thanks again for this update. It worked perfectly.
